#!/usr/bin/env bash
# Configures Mosquitto for this POC:
#   * MQTT over TLS on port 8883 (no plain-text listener)
#   * username/password login (taken from settings.py)
#   * topic permissions (ACL): the edge can only publish audio, the server can only answer
#
# Usage (after: sudo apt install mosquitto mosquitto-clients  and  bash broker/make_certs.sh):
#   sudo bash broker/install_broker.sh
set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Please run with sudo:  sudo bash broker/install_broker.sh"; exit 1; }
cd "$(dirname "$0")"
command -v mosquitto >/dev/null || { echo "Install Mosquitto first:  sudo apt install mosquitto mosquitto-clients"; exit 1; }
[[ -f certs/server.crt ]] || { echo "Create certificates first:  bash broker/make_certs.sh"; exit 1; }

# Read users/passwords/topic prefix from settings.py so everything always matches.
mapfile -t CFG < <(cd .. && python3 -c "
import settings as s
print(s.EDGE_MQTT_USER); print(s.EDGE_MQTT_PASSWORD)
print(s.SERVER_MQTT_USER); print(s.SERVER_MQTT_PASSWORD)
print(s.TOPIC_PREFIX); print(s.BROKER_PORT)")
EDGE_USER="${CFG[0]}"; EDGE_PASS="${CFG[1]}"
SERVER_USER="${CFG[2]}"; SERVER_PASS="${CFG[3]}"
PREFIX="${CFG[4]}"; PORT="${CFG[5]}"

echo "[1/5] Copying TLS certificates to /etc/mosquitto/certs"
mkdir -p /etc/mosquitto/certs
install -o mosquitto -g mosquitto -m 644 certs/ca.crt     /etc/mosquitto/certs/pqc-ca.crt
install -o mosquitto -g mosquitto -m 644 certs/server.crt /etc/mosquitto/certs/pqc-server.crt
install -o mosquitto -g mosquitto -m 600 certs/server.key /etc/mosquitto/certs/pqc-server.key

echo "[2/5] Creating MQTT users: ${EDGE_USER}, ${SERVER_USER}"
rm -f /etc/mosquitto/pqc_passwd
touch /etc/mosquitto/pqc_passwd
chmod 600 /etc/mosquitto/pqc_passwd
mosquitto_passwd -b /etc/mosquitto/pqc_passwd "$EDGE_USER" "$EDGE_PASS"
mosquitto_passwd -b /etc/mosquitto/pqc_passwd "$SERVER_USER" "$SERVER_PASS"
chown mosquitto:mosquitto /etc/mosquitto/pqc_passwd

echo "[3/5] Writing topic permissions (ACL)"
cat > /etc/mosquitto/pqc_acl <<EOF
# Edge device: may only send registration, session start, audio and disconnect
user ${EDGE_USER}
topic write ${PREFIX}/register
topic write ${PREFIX}/session/start
topic write ${PREFIX}/+/audio
topic write ${PREFIX}/+/audio/disconnect
topic read ${PREFIX}/device/+/status

# Server: reads everything under the prefix, answers on status topics
user ${SERVER_USER}
topic read ${PREFIX}/#
topic write ${PREFIX}/device/+/status
EOF
chown mosquitto:mosquitto /etc/mosquitto/pqc_acl
chmod 600 /etc/mosquitto/pqc_acl

echo "[4/5] Writing /etc/mosquitto/conf.d/pqc_poc.conf"
cat > /etc/mosquitto/conf.d/pqc_poc.conf <<EOF
# PQC voice POC - MQTT over TLS only (generated by broker/install_broker.sh)
listener ${PORT}
cafile /etc/mosquitto/certs/pqc-ca.crt
certfile /etc/mosquitto/certs/pqc-server.crt
keyfile /etc/mosquitto/certs/pqc-server.key
tls_version tlsv1.3

allow_anonymous false
password_file /etc/mosquitto/pqc_passwd
acl_file /etc/mosquitto/pqc_acl
EOF

echo "[5/5] Restarting Mosquitto"
systemctl enable mosquitto >/dev/null 2>&1 || true
systemctl restart mosquitto
sleep 1
if systemctl is-active --quiet mosquitto; then
  echo
  echo "OK: Mosquitto is running with TLS 1.3 on port ${PORT}"
else
  echo "Mosquitto failed to start. Last log lines:"
  journalctl -u mosquitto -n 30 --no-pager
  exit 1
fi

if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
  echo "Note: the firewall (ufw) is active. If the edge device is ANOTHER machine, run:"
  echo "      sudo ufw allow ${PORT}/tcp"
fi
